export const EmptyFieldError = "Это обязательное поле"
export const InvalidPhoneError = "Вы уверены, что это номер телефона?\nРекомендуемый формат : +380XXXXXXXXX"
export const InvalidEmailError = "Указан неверный e-mail"
export const InputTooLongError = "Введенная строка должна не превышать %s символов"
export const InputTooShortError = "Введенная строка должна быть длиннее %s символов"
export const MessageTooDetailedError = "Вы уверены, что вы не поэму пишите?"